// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalabaIlova.Data;

#nullable disable

namespace TalabaIlova.Migrations
{
    [DbContext(typeof(TalabaContext))]
    partial class TalabaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TalabaIlova.Models.Talaba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Familiya")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ism")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yosh")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Talabalar");
                });
#pragma warning restore 612, 618
        }
    }
}
